# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_ups.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61mazon_ups.proto\"?\n\tException\x12\x0c\n\x04info\x18\x01 \x02(\t\x12\x14\n\x0coriginseqnum\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x05\"-\n\tWarehouse\x12\n\n\x02id\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\"9\n\x07Product\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"b\n\tATruckReq\x12\x16\n\x02wh\x18\x01 \x02(\x0b\x32\n.Warehouse\x12\x11\n\tpackageid\x18\x02 \x02(\x03\x12\x1a\n\x08products\x18\x03 \x03(\x0b\x32\x08.Product\x12\x0e\n\x06seqnum\x18\x04 \x02(\x05\"u\n\x0b\x41\x44\x65liverReq\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x12\n\nupsaccount\x18\x02 \x01(\x05\x12\x0f\n\x07truckid\x18\x03 \x02(\x05\x12\x0e\n\x06\x64\x65st_x\x18\x04 \x02(\x05\x12\x0e\n\x06\x64\x65st_y\x18\x05 \x02(\x05\x12\x0e\n\x06seqnum\x18\x06 \x02(\x05\"0\n\x0bUDeliverRsp\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0e\n\x06seqnum\x18\x02 \x02(\x05\"@\n\nUTruckSent\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x11\n\tpackageid\x18\x02 \x02(\x03\x12\x0e\n\x06seqnum\x18\x03 \x02(\x05\"C\n\rUTruckArrived\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x11\n\tpackageid\x18\x02 \x02(\x03\x12\x0e\n\x06seqnum\x18\x03 \x02(\x05\"-\n\nU2AWorldId\x12\x0f\n\x07worldid\x18\x01 \x02(\x05\x12\x0e\n\x06seqnum\x18\x02 \x02(\x05\"m\n\x04\x41Msg\x12\x1c\n\x08truckreq\x18\x01 \x03(\x0b\x32\n.ATruckReq\x12 \n\ndeliverreq\x18\x02 \x03(\x0b\x32\x0c.ADeliverReq\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x05\x12\x17\n\x03\x65rr\x18\x04 \x03(\x0b\x32\n.Exception\"\xb2\x01\n\x04UMsg\x12\x1f\n\tdelivered\x18\x01 \x03(\x0b\x32\x0c.UDeliverRsp\x12\x1e\n\ttrucksent\x18\x02 \x03(\x0b\x32\x0b.UTruckSent\x12$\n\x0ctruckarrived\x18\x03 \x03(\x0b\x32\x0e.UTruckArrived\x12\x1c\n\x07worldid\x18\x04 \x03(\x0b\x32\x0b.U2AWorldId\x12\x0c\n\x04\x61\x63ks\x18\x05 \x03(\x05\x12\x17\n\x03\x65rr\x18\x06 \x03(\x0b\x32\n.Exception')



_EXCEPTION = DESCRIPTOR.message_types_by_name['Exception']
_WAREHOUSE = DESCRIPTOR.message_types_by_name['Warehouse']
_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_ATRUCKREQ = DESCRIPTOR.message_types_by_name['ATruckReq']
_ADELIVERREQ = DESCRIPTOR.message_types_by_name['ADeliverReq']
_UDELIVERRSP = DESCRIPTOR.message_types_by_name['UDeliverRsp']
_UTRUCKSENT = DESCRIPTOR.message_types_by_name['UTruckSent']
_UTRUCKARRIVED = DESCRIPTOR.message_types_by_name['UTruckArrived']
_U2AWORLDID = DESCRIPTOR.message_types_by_name['U2AWorldId']
_AMSG = DESCRIPTOR.message_types_by_name['AMsg']
_UMSG = DESCRIPTOR.message_types_by_name['UMsg']
Exception = _reflection.GeneratedProtocolMessageType('Exception', (_message.Message,), {
  'DESCRIPTOR' : _EXCEPTION,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:Exception)
  })
_sym_db.RegisterMessage(Exception)

Warehouse = _reflection.GeneratedProtocolMessageType('Warehouse', (_message.Message,), {
  'DESCRIPTOR' : _WAREHOUSE,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:Warehouse)
  })
_sym_db.RegisterMessage(Warehouse)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:Product)
  })
_sym_db.RegisterMessage(Product)

ATruckReq = _reflection.GeneratedProtocolMessageType('ATruckReq', (_message.Message,), {
  'DESCRIPTOR' : _ATRUCKREQ,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ATruckReq)
  })
_sym_db.RegisterMessage(ATruckReq)

ADeliverReq = _reflection.GeneratedProtocolMessageType('ADeliverReq', (_message.Message,), {
  'DESCRIPTOR' : _ADELIVERREQ,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ADeliverReq)
  })
_sym_db.RegisterMessage(ADeliverReq)

UDeliverRsp = _reflection.GeneratedProtocolMessageType('UDeliverRsp', (_message.Message,), {
  'DESCRIPTOR' : _UDELIVERRSP,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UDeliverRsp)
  })
_sym_db.RegisterMessage(UDeliverRsp)

UTruckSent = _reflection.GeneratedProtocolMessageType('UTruckSent', (_message.Message,), {
  'DESCRIPTOR' : _UTRUCKSENT,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UTruckSent)
  })
_sym_db.RegisterMessage(UTruckSent)

UTruckArrived = _reflection.GeneratedProtocolMessageType('UTruckArrived', (_message.Message,), {
  'DESCRIPTOR' : _UTRUCKARRIVED,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UTruckArrived)
  })
_sym_db.RegisterMessage(UTruckArrived)

U2AWorldId = _reflection.GeneratedProtocolMessageType('U2AWorldId', (_message.Message,), {
  'DESCRIPTOR' : _U2AWORLDID,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:U2AWorldId)
  })
_sym_db.RegisterMessage(U2AWorldId)

AMsg = _reflection.GeneratedProtocolMessageType('AMsg', (_message.Message,), {
  'DESCRIPTOR' : _AMSG,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AMsg)
  })
_sym_db.RegisterMessage(AMsg)

UMsg = _reflection.GeneratedProtocolMessageType('UMsg', (_message.Message,), {
  'DESCRIPTOR' : _UMSG,
  '__module__' : 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UMsg)
  })
_sym_db.RegisterMessage(UMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXCEPTION._serialized_start=20
  _EXCEPTION._serialized_end=83
  _WAREHOUSE._serialized_start=85
  _WAREHOUSE._serialized_end=130
  _PRODUCT._serialized_start=132
  _PRODUCT._serialized_end=189
  _ATRUCKREQ._serialized_start=191
  _ATRUCKREQ._serialized_end=289
  _ADELIVERREQ._serialized_start=291
  _ADELIVERREQ._serialized_end=408
  _UDELIVERRSP._serialized_start=410
  _UDELIVERRSP._serialized_end=458
  _UTRUCKSENT._serialized_start=460
  _UTRUCKSENT._serialized_end=524
  _UTRUCKARRIVED._serialized_start=526
  _UTRUCKARRIVED._serialized_end=593
  _U2AWORLDID._serialized_start=595
  _U2AWORLDID._serialized_end=640
  _AMSG._serialized_start=642
  _AMSG._serialized_end=751
  _UMSG._serialized_start=754
  _UMSG._serialized_end=932
# @@protoc_insertion_point(module_scope)
